<a href="https://colab.research.google.com/github/liamlucca/Curso-Pytorch-00_pytorch_fundamentals_exercises/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(7,7)
tensor_A, tensor_A.shape

(tensor([[0.0328, 0.1007, 0.4424, 0.8791, 0.1275, 0.8553, 0.4683],
         [0.0193, 0.6651, 0.7621, 0.1695, 0.2086, 0.4055, 0.8818],
         [0.3693, 0.7476, 0.6187, 0.2468, 0.2594, 0.3679, 0.2272],
         [0.8756, 0.1566, 0.4574, 0.2513, 0.5913, 0.9310, 0.4118],
         [0.7569, 0.2214, 0.0854, 0.4268, 0.1292, 0.9072, 0.0525],
         [0.8437, 0.9081, 0.7940, 0.7176, 0.3432, 0.8645, 0.9598],
         [0.8596, 0.2489, 0.7931, 0.5137, 0.9299, 0.6707, 0.4159]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_B = torch.rand(1, 7)

# Perform matrix multiplication 
torch.mul(tensor_A, tensor_B)

tensor([[2.7099e-02, 8.9182e-02, 4.2039e-02, 4.5099e-01, 4.0328e-02, 3.6034e-02,
         3.7985e-03],
        [1.5974e-02, 5.8886e-01, 7.2422e-02, 8.6981e-02, 6.5969e-02, 1.7084e-02,
         7.1529e-03],
        [3.0553e-01, 6.6193e-01, 5.8795e-02, 1.2660e-01, 8.2060e-02, 1.5500e-02,
         1.8427e-03],
        [7.2432e-01, 1.3861e-01, 4.3469e-02, 1.2891e-01, 1.8703e-01, 3.9227e-02,
         3.3406e-03],
        [6.2614e-01, 1.9605e-01, 8.1144e-03, 2.1898e-01, 4.0867e-02, 3.8223e-02,
         4.2600e-04],
        [6.9797e-01, 8.0402e-01, 7.5457e-02, 3.6813e-01, 1.0856e-01, 3.6424e-02,
         7.7856e-03],
        [7.1111e-01, 2.2042e-01, 7.5373e-02, 2.6352e-01, 2.9411e-01, 2.8257e-02,
         3.3742e-03]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_C = torch.rand(3,4)
tensor_D = torch.rand(4,3)


# Matrix multiply tensors
torch.mm(tensor_C, tensor_D)

tensor([[0.5445, 0.6972, 0.9362],
        [1.2350, 0.9886, 1.7153],
        [0.7619, 0.7761, 1.2287]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor_E = torch.rand(2, 3).to(device)
tensor_F = torch.rand(2, 3).to(device)

tensor_E, tensor_F

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_G = torch.matmul(tensor_E, tensor_F.T)
tensor_G

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = torch.max(tensor_G)

# Find min
min = torch.min(tensor_G)

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
argmax = torch.argmax(tensor_G)

# Find arg min
argmin = torch.argmin(tensor_G)

argmax, argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_I = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_J = tensor_I.squeeze()

# Print out tensors and their shapes
tensor_I, tensor_J


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))